In [1]:
import pandas as pd
import os
import glob

In [5]:
os.chdir(r"C:\Users\sarfaraz\Downloads\AReM\walking")

In [11]:
os.getcwd()

'C:\\Users\\sarfaraz\\Downloads\\AReM\\walking'

In [12]:
os.listdir()

['dataset1.csv',
 'dataset10.csv',
 'dataset11.csv',
 'dataset12.csv',
 'dataset13.csv',
 'dataset14.csv',
 'dataset15.csv',
 'dataset2.csv',
 'dataset3.csv',
 'dataset4.csv',
 'dataset5.csv',
 'dataset6.csv',
 'dataset7.csv',
 'dataset8.csv',
 'dataset9.csv']

In [14]:
pd.read_csv("dataset1.csv",skiprows=4)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,35.00,3.67,16.50,3.77,14.00,1.63
1,250,28.50,3.35,17.50,3.77,12.25,3.90
2,500,35.50,2.87,15.75,2.86,17.75,5.07
3,750,29.75,12.19,16.25,2.17,20.75,2.59
4,1000,27.00,2.12,16.75,0.83,24.75,1.64
...,...,...,...,...,...,...,...
475,118750,35.50,4.27,15.67,4.78,17.00,1.41
476,119000,30.75,2.49,18.50,4.15,18.00,1.41
477,119250,36.00,2.94,16.25,1.30,16.67,3.09
478,119500,37.40,6.15,10.25,5.31,14.60,4.32
479,119750,34.67,1.25,18.00,1.87,9.33,6.02

In [ ]:
# importing libraries
import pandas as pd
import glob
import os
  
# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\walking", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df = pd.concat(pd.read_csv((str[i for i in joined_list]), skiprows=4), ignore_index=True)
print(df)

In [17]:
joined_list

[]

In [32]:
# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\walking", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

In [33]:
type(joined_list)

list

In [28]:
lista = []
for i in joined_list:
    lista.append(i)

In [46]:
joined_list[1]

'C:\\Users\\sarfaraz\\Downloads\\AReM\\walking\\dataset10.csv'

In [40]:
numbers = (range(1,16))
result = map([i for i in joined_list],numbers)
print(result)

<map object at 0x0000028B665F9F10>

In [49]:
[j for j in joined_list[i]]

NameError: name 'i' is not defined

In [58]:
df_append = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append = df_append.append(df_temp, ignore_index=True)
df_append

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1554134334.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,35.00,3.67,16.50,3.77,14.00,1.63
1,250,28.50,3.35,17.50,3.77,12.25,3.90
2,500,35.50,2.87,15.75,2.86,17.75,5.07
3,750,29.75,12.19,16.25,2.17,20.75,2.59
4,1000,27.00,2.12,16.75,0.83,24.75,1.64
...,...,...,...,...,...,...,...
7195,118750,31.50,1.66,12.50,3.20,14.25,4.44
7196,119000,27.33,1.25,11.33,0.94,20.00,4.00
7197,119250,37.80,7.68,14.20,2.48,17.25,0.83
7198,119500,33.75,1.30,15.75,5.21,16.50,2.69
7199,119750,32.67,3.09,18.67,0.47,14.00,3.16

In [59]:
# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\walking", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_walking = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
df_append_walking

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3601481520.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_walking = df_append_walking.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,35.00,3.67,16.50,3.77,14.00,1.63
1,250,28.50,3.35,17.50,3.77,12.25,3.90
2,500,35.50,2.87,15.75,2.86,17.75,5.07
3,750,29.75,12.19,16.25,2.17,20.75,2.59
4,1000,27.00,2.12,16.75,0.83,24.75,1.64
...,...,...,...,...,...,...,...
7195,118750,31.50,1.66,12.50,3.20,14.25,4.44
7196,119000,27.33,1.25,11.33,0.94,20.00,4.00
7197,119250,37.80,7.68,14.20,2.48,17.25,0.83
7198,119500,33.75,1.30,15.75,5.21,16.50,2.69
7199,119750,32.67,3.09,18.67,0.47,14.00,3.16

In [60]:
df_append_walking["label"] = "walking"

In [61]:
df_append_walking

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,35.00,3.67,16.50,3.77,14.00,1.63,walking
1,250,28.50,3.35,17.50,3.77,12.25,3.90,walking
2,500,35.50,2.87,15.75,2.86,17.75,5.07,walking
3,750,29.75,12.19,16.25,2.17,20.75,2.59,walking
4,1000,27.00,2.12,16.75,0.83,24.75,1.64,walking
...,...,...,...,...,...,...,...,...
7195,118750,31.50,1.66,12.50,3.20,14.25,4.44,walking
7196,119000,27.33,1.25,11.33,0.94,20.00,4.00,walking
7197,119250,37.80,7.68,14.20,2.48,17.25,0.83,walking
7198,119500,33.75,1.30,15.75,5.21,16.50,2.69,walking
7199,119750,32.67,3.09,18.67,0.47,14.00,3.16,walking

In [62]:
df_append_walking.to_csv("walking_merge.csv")

In [63]:
pd.read_csv("walking_merge.csv")

,Unnamed: 0,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,0,35.00,3.67,16.50,3.77,14.00,1.63,walking
1,1,250,28.50,3.35,17.50,3.77,12.25,3.90,walking
2,2,500,35.50,2.87,15.75,2.86,17.75,5.07,walking
3,3,750,29.75,12.19,16.25,2.17,20.75,2.59,walking
4,4,1000,27.00,2.12,16.75,0.83,24.75,1.64,walking
...,...,...,...,...,...,...,...,...,...
7195,7195,118750,31.50,1.66,12.50,3.20,14.25,4.44,walking
7196,7196,119000,27.33,1.25,11.33,0.94,20.00,4.00,walking
7197,7197,119250,37.80,7.68,14.20,2.48,17.25,0.83,walking
7198,7198,119500,33.75,1.30,15.75,5.21,16.50,2.69,walking
7199,7199,119750,32.67,3.09,18.67,0.47,14.00,3.16,walking

In [64]:
# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\standing", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_standing = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
df_append_standing

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\739575137.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_standing = df_append_standing.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,46.50,0.50,11.50,0.50,20.33,0.94
1,250,46.50,0.50,12.00,0.00,20.25,0.43
2,500,46.50,0.50,12.00,0.00,20.50,0.50
3,750,46.50,0.50,12.75,0.43,19.50,0.50
4,1000,46.50,0.50,13.25,0.43,18.75,0.43
...,...,...,...,...,...,...,...
7195,118750,44.50,0.50,18.75,0.83,5.25,1.79
7196,119000,44.50,0.50,19.33,0.47,6.00,0.82
7197,119250,44.50,0.50,19.25,0.83,7.25,1.30
7198,119500,44.50,0.50,19.00,0.71,8.00,0.71
7199,119750,44.67,0.47,18.00,0.00,9.00,0.00

In [66]:
df_append_standing["label"] = "standing"
df_append_standing

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,46.50,0.50,11.50,0.50,20.33,0.94,standing
1,250,46.50,0.50,12.00,0.00,20.25,0.43,standing
2,500,46.50,0.50,12.00,0.00,20.50,0.50,standing
3,750,46.50,0.50,12.75,0.43,19.50,0.50,standing
4,1000,46.50,0.50,13.25,0.43,18.75,0.43,standing
...,...,...,...,...,...,...,...,...
7195,118750,44.50,0.50,18.75,0.83,5.25,1.79,standing
7196,119000,44.50,0.50,19.33,0.47,6.00,0.82,standing
7197,119250,44.50,0.50,19.25,0.83,7.25,1.30,standing
7198,119500,44.50,0.50,19.00,0.71,8.00,0.71,standing
7199,119750,44.67,0.47,18.00,0.00,9.00,0.00,standing

In [73]:
import pandas as pd
import os
import glob

# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\sitting", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_sitting = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
df_append_sitting

df_append_sitting["label"] = "sitting"
df_append_sitting

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\632170400.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_sitting = df_append_sitting.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,42.0,0.0,19.20,0.98,15.50,2.06,sitting
1,250,42.0,0.0,19.33,0.94,11.00,0.82,sitting
2,500,42.0,0.0,17.50,0.50,12.50,0.50,sitting
3,750,42.0,0.0,17.00,1.41,13.33,0.94,sitting
4,1000,42.0,0.0,17.50,0.87,12.00,0.82,sitting
...,...,...,...,...,...,...,...,...
7194,118750,42.0,0.0,20.50,0.87,18.50,0.50,sitting
7195,119000,42.0,0.0,21.25,0.43,17.50,0.50,sitting
7196,119250,42.0,0.0,21.00,0.00,16.00,0.82,sitting
7197,119500,42.0,0.0,21.00,0.00,18.25,0.43,sitting
7198,119750,42.0,0.0,21.00,0.00,16.67,0.47,sitting

In [74]:
import pandas as pd
import os
import glob

# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\lying", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_lying = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
df_append_lying

# Adding an extra column
df_append_lying["label"] = "lying"
df_append_lying

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3769996735.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_lying = df_append_lying.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,29.00,0.00,9.00,0.71,8.50,0.50,lying
1,250,29.00,0.00,8.00,0.71,8.50,0.50,lying
2,500,29.00,0.00,8.00,0.71,8.00,1.00,lying
3,750,28.50,0.50,8.25,0.43,8.75,0.43,lying
4,1000,29.00,0.00,8.75,1.09,9.00,0.00,lying
...,...,...,...,...,...,...,...,...
7195,118750,41.50,0.50,10.67,0.47,14.00,0.82,lying
7196,119000,41.50,0.50,10.80,0.40,14.40,0.80,lying
7197,119250,41.75,0.43,10.00,0.00,13.67,0.94,lying
7198,119500,42.00,0.00,9.40,0.49,14.00,1.10,lying
7199,119750,41.75,0.43,9.00,0.00,14.33,0.47,lying

In [76]:
import pandas as pd
import os
import glob

# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\cycling", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_cycling = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)
df_append_cycling

# Adding an extra column
df_append_cycling["label"] = "cycling"
df_append_cycling

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1465311979.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1465311979.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1465311979.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1465311979.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\1465311979.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_cycling = df_append_cycling.append(df_temp, ignore_index=True)

ParserError: Error tokenizing data. C error: Expected 7 fields in line 485, saw 8

In [78]:
import pandas as pd
import os
import glob

# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\bending2", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_bending2 = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
df_append_bending2

# Adding an extra column
df_append_bending2["label"] = "bending2"
df_append_bending2

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3426427248.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending2 = df_append_bending2.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,23.75,0.43,24.00,0.00,24.67,0.47,bending2
1,250,22.67,0.94,24.00,0.00,24.67,0.94,bending2
2,500,21.33,0.47,24.00,0.00,24.75,0.83,bending2
3,750,21.00,0.00,24.00,0.00,25.25,1.09,bending2
4,1000,23.00,0.71,23.75,0.43,24.75,0.83,bending2
...,...,...,...,...,...,...,...,...
2875,118750,27.00,0.00,14.00,0.00,6.50,0.50,bending2
2876,119000,27.00,0.00,15.00,0.00,4.00,1.00,bending2
2877,119250,27.00,0.00,14.25,0.83,4.00,2.00,bending2
2878,119500,27.00,0.00,13.33,1.25,1.50,0.50,bending2
2879,119750,26.50,0.50,15.00,0.00,3.00,0.00,bending2

In [77]:
import pandas as pd
import os
import glob

# merging the files
joined_files = os.path.join(r"C:\Users\sarfaraz\Downloads\AReM\bending1", "dataset*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

df_append_bending1 = pd.DataFrame()
#append all files together
for file in joined_list:
            df_temp = pd.read_csv(file, skiprows=4)
            df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
df_append_bending1

# Adding an extra column
df_append_bending1["label"] = "bending1"
df_append_bending1

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)
C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\2690940391.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append_bending1 = df_append_bending1.append(df_temp, ignore_index=True)

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,39.25,0.43,22.75,0.43,33.75,1.30,bending1
1,250,39.25,0.43,23.00,0.00,33.00,0.00,bending1
2,500,39.25,0.43,23.25,0.43,33.00,0.00,bending1
3,750,39.50,0.50,23.00,0.71,33.00,0.00,bending1
4,1000,39.50,0.50,24.00,0.00,33.00,0.00,bending1
...,...,...,...,...,...,...,...,...
3355,118750,44.25,0.83,16.25,1.30,24.00,0.00,bending1
3356,119000,44.00,0.71,11.00,1.00,24.00,0.00,bending1
3357,119250,44.25,0.43,10.25,1.30,22.75,0.83,bending1
3358,119500,43.75,0.43,7.33,2.87,21.50,0.50,bending1
3359,119750,44.50,0.50,3.00,1.22,21.50,0.50,bending1

In [79]:
df_merge_all = df_append_walking.append([df_append_standing,df_append_sitting,df_append_lying,df_append_bending1,df_append_bending2])

C:\Users\sarfaraz\AppData\Local\Temp\ipykernel_9464\3586764505.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_merge_all = df_append_walking.append([df_append_standing,df_append_sitting,df_append_lying,df_append_bending1,df_append_bending2])

In [80]:
df_merge_all

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,label
0,0,35.00,3.67,16.50,3.77,14.00,1.63,walking
1,250,28.50,3.35,17.50,3.77,12.25,3.90,walking
2,500,35.50,2.87,15.75,2.86,17.75,5.07,walking
3,750,29.75,12.19,16.25,2.17,20.75,2.59,walking
4,1000,27.00,2.12,16.75,0.83,24.75,1.64,walking
...,...,...,...,...,...,...,...,...
2875,118750,27.00,0.00,14.00,0.00,6.50,0.50,bending2
2876,119000,27.00,0.00,15.00,0.00,4.00,1.00,bending2
2877,119250,27.00,0.00,14.25,0.83,4.00,2.00,bending2
2878,119500,27.00,0.00,13.33,1.25,1.50,0.50,bending2
2879,119750,26.50,0.50,15.00,0.00,3.00,0.00,bending2

In [81]:
set(df_merge_all["label"])

{'bending1', 'bending2', 'lying', 'sitting', 'standing', 'walking'}

In [84]:
os.listdir()

['.ipynb_checkpoints',
 'dataset1.csv',
 'dataset10.csv',
 'dataset11.csv',
 'dataset12.csv',
 'dataset13.csv',
 'dataset14.csv',
 'dataset15.csv',
 'dataset2.csv',
 'dataset3.csv',
 'dataset4.csv',
 'dataset5.csv',
 'dataset6.csv',
 'dataset7.csv',
 'dataset8.csv',
 'dataset9.csv']

In [85]:
os.getcwd()

'C:\\Users\\sarfaraz\\Downloads\\AReM\\walking'

In [87]:
os.chdir(r"C:\Users\sarfaraz\Downloads\AReM")

In [88]:
os.getcwd()

'C:\\Users\\sarfaraz\\Downloads\\AReM'

In [89]:
df_merge_all.to_csv("merged_file.csv")